[tool.poetry]
name = "release-volume-sampler"
version = "0.1.0"
description = "Module designed to sample potential submarine release volumes triggered by earthquakes."
authors = ["Erlend Briseid Storrøsten <erlend.briseid.storrosten@ngi.no>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
