import json
import pandas as pd
import rasterio
import os
import numpy as np
import matplotlib.pyplot as plt
from src.utils.logging import setup_logger
from src.utils.utils import create_dir
from scipy.signal import convolve2d


def main():
    """ To ensure that module imports works, run the script as a module.
    release-volume-sampler$ python -m src/volume_sampler.volume_writer
    """
    # Usage example
    config = {
        "rundir": "/home/ebr/projects/release-volume-sampler/generated/messina_001",
    }
    
    write_config = {
        "write_rasters": True,
        "tsunami_potential_ratio_threshold": 1.,
        "max_rasters": 1000,
    }
    
    # Execute
    writer = VolumeWriter(**config)
    writer.write_volumes(**write_config)
    writer.plot_distribution()

class VolumeWriter:
    """
    Class designed for processing of volumes generated by the sampling process. 
    
    Tasks:
    1. Filter volumes based on the tsunamogenic potential. Using statistical relations.
    2. Assign thickness (Statistically from total area), smooth and create raster files.
    3. Make figures to obtain an overview of the distribution.
    4. Assign probabilities from shakemaps. #TODO
    
    """
    def __init__(self, rundir):
        
        self.rundir = rundir
        self.output_dir = os.path.join(rundir, "volumes")
        self.triangulation_dir = os.path.join(rundir, "triangulation")
        self.tri_mask_path = os.path.join(self.triangulation_dir, "triangulation.tif")
        self.logger = setup_logger("volume_writer", self.output_dir)
        
        self.load_volumes()
        self.assign_thickness()
        self.assign_tsunami_potential_ratio()

 
    def load_volumes(self):
        """Load volumes from sampler.
        """
        with open(os.path.join(self.output_dir, "recursive_propagations.json"), "r") as f:
            data = json.load(f)
        
        # Load json with volumes into dataframe.
        self.df = pd.json_normalize(
            data,
            record_path=["volumes"],  # Extract and flatten the "volumes" list
            meta=["seed_triangle", "seed_triangle_probability"]  # Include these fields as metadata
        ).astype({"seed_triangle": int, "seed_triangle_probability": float})
        self.df.drop(columns=["steps"], inplace=True)
        self.df['id'] = self.df.index
        
        # Use seed probability to set final probability
        self.df["probability"] = self.df.seed_triangle_probability*self.df.condprob
        self.df["probability"] = self.df["probability"]/self.df["probability"].sum()
        
    
    def assign_thickness(self):
        """Statistical relation for assigning thickness of the volume (Zengafinnen-Morris et al. 2022).
        V = 0.0298*A^{1.36}
        """
        self.df["volume"] = 0.0298*self.df.area**1.36
        self.df["thickness"] = self.df.volume/self.df.area
    
    
    def assign_tsunami_potential_ratio(self):
        """Estimate tsunami potential.
        
        Based on equations of Watts et al. (2005). 
        V_{min}=0.0957*slope^{-1.609}*thickness^{1.3807} where V_{min} is the minimum volume
        that can create a significant tsunami for a given water depth H (in m) and slope angle
        (in degrees) and V_{min} in Mm^{3}.
        
        Note: This ratio goes to infinity as H goes to zero.
        """
        self.df["tsunami_potential_ratio"] = self.df.volume/(0.0957*(self.df.mean_slope**-1.609)*((0-self.df.mean_elevation)**1.3807)*1e6)
        
    
    def write_volumes(self, write_rasters=True, tsunami_potential_ratio_threshold=1., max_rasters=1000):
        """ Write csv with all volumes. Volumes are sorted according to tsunami_potential_ratio_threshold.
        """
        self.df.drop(columns=["released"]).to_csv(os.path.join(self.output_dir, "volumes.csv"),
                                                  float_format="%.6e")
        if write_rasters:
            rasterdir = os.path.join(self.output_dir, "rasters")
            create_dir(rasterdir, logger=self.logger, clear=True)
            with rasterio.open(self.tri_mask_path) as src:
                tri_mask = src.read(1)  # Read the triangle mask
                tri_profile = src.profile  # Copy metadata to use in output

            # Update profile for single-band, unsigned 8-bit data
            tri_profile.update(dtype=rasterio.float32, count=1)
            #tri_profile.update(driver="AAIGrid") # Write asci files.
            
            df_filtered = self.df[self.df.tsunami_potential_ratio > tsunami_potential_ratio_threshold]
            df_filtered = df_filtered.sort_values("tsunami_potential_ratio", ascending=False)
            
            for i, volume in df_filtered.iloc[:max_rasters].iterrows():
                # Create binary volume mask: 1 if pixel belongs to specified triangles, else 0
                volume_mask = np.isin(tri_mask, volume.released)
                
                # Smooth volume
                volume_raster = convolve2d(volume_mask.astype(float)*volume.thickness, np.ones((3,3))/9., mode="same")
                volume_path = os.path.join(self.output_dir, f"rasters/volume_seed-{volume.seed_triangle}_area-{volume.area:.2e}_id-{volume.id}.tif")

                with rasterio.open(volume_path, 'w', **tri_profile) as dst:
                    dst.write(volume_raster.astype(rasterio.float32), 1)  # Write volume to file
                self.logger.info(f"Wrote volume raster:{volume_path}")
        

    def plot_distribution(self):
        """Create figures to display the volume distribution.
        """
        
        # Create a figure and axis objects
        fig, axes = plt.subplots(2, 2, figsize=(12, 8))  # 2 rows, 2 columns of plots
        fig.suptitle("Release Characteristics", fontsize=16)

        # Top-left: Histogram of area
        axes[0, 0].hist(self.df.area, bins=30, color="skyblue", edgecolor="black")
        axes[0, 0].set_title("Area of Release")
        axes[0, 0].set_xlabel("Area")
        axes[0, 0].set_ylabel("Frequency")

        # Top-right: Histogram of thickness
        axes[0, 1].hist(self.df.thickness, bins=30, color="lightgreen", edgecolor="black")
        axes[0, 1].set_title("Thickness of Release")
        axes[0, 1].set_xlabel("Thickness")
        axes[0, 1].set_ylabel("Frequency")

        # Bottom-left: Weighted histogram of area
        axes[1, 0].hist(self.df.area, bins=30, weights=self.df.probability, color="salmon", edgecolor="black")
        axes[1, 0].set_title("Weighted Area of Release")
        axes[1, 0].set_xlabel("Area")
        axes[1, 0].set_ylabel("Weighted Frequency")

        # Bottom-right: Weighted histogram of thickness
        axes[1, 1].hist(self.df.thickness, bins=30, weights=self.df.probability, color="orange", edgecolor="black")
        axes[1, 1].set_title("Weighted Thickness of Release")
        axes[1, 1].set_xlabel("Thickness")
        axes[1, 1].set_ylabel("Weighted Frequency")

        plt.tight_layout(rect=[0, 0, 1, 0.96])  # Leave space for the main title
        plt.savefig(os.path.join(self.output_dir, "release_characteristics.png"))  # Save as an image file


if __name__ == "__main__":
    main()